config/routes.rb
Rails.application.routes.draw do

  root 'alarms#index'
  resources :alarms do
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alarm.rb
class Alarm < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]
  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(alarm_params)
    respond_to do |format|
      if @alarm.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(:alarms, partial: "alarms/alarm",
                                                   locals:             { alarm: @alarm }, formats: :html)
        end
        format.html { redirect_to @alarm, notice: 'Alarm was successfully created.' }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@alarm) }
        format.html { redirect_to @alarm, notice: 'Alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@alarm) }
      format.html { redirect_to alarms_url, notice: 'Alarm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_alarm
    @alarm = Alarm.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def alarm_params
    params.require(:alarm).permit(:datetime, :rule, :active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alarms/_alarm.html.erb
<div id=<%= dom_id(alarm) %> class="alarm">
  <div class="columns">
    <div class="column is-8">
        <span class="icon has-text-info">
            <i class="far fa-clock"></i>
          </span>
        <%= link_to alarm.datetime.to_s(:time), alarm %>
    </div>
    <div class="column is-2">
        <%= button_to alarm, method: :patch, params: { alarm: {active: alarm.active? ? 0 : 1 }} do %>
            <span class="icon has-text-info">
              <i class="fas fa-2x fa-toggle-<%= alarm.active? ? 'on' : 'off' %>"></i>
            </span>
        <% end %>
    </div>
    <div class="column is-2">
        <%= button_to alarm, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')" do %>
              <span class="icon has-text-danger" style="{float: right;}">
                <i class="fas fa-2x fa-times-circle"></i>
              </span>
        <% end %>
    </div>
  </div>
</div>

app/views/alarms/_form.html.erb
<%= form_with(model: alarm) do |form| %>
  <% if alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
        <% alarm.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field is-horizontal is-grouped is-grouped-centered">
    <div class="control">
      <%= form.time_select :datetime %>
    </div>


    <div class="control">
      <%= form.submit "Nouvelle alarme"%>
    </div>
  </div>
<% end %>

app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<p id="notice"><%= notice %></p>
<div class="alarms_container">
  <header>
    <div class="columns">
      <div class="column">
        Alarmes
      </div>
    </div>
  </header>
  <section class="form">
    <%= render "form", alarm: Alarm.new %>
  </section>
  <section>
    <turbo-frame id="alarms">
      <%= render partial: 'alarm', collection: @alarms %>
    </turbo-frame>
  </section>
  <footer>

  </footer>
</div>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Back', alarms_path %>

app/views/alarms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datetime:</strong>
  <%= @alarm.datetime %>
</p>

<p>
  <strong>Rule:</strong>
  <%= @alarm.rule %>
</p>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> |
<%= link_to 'Back', alarms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JadeClock</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= turbo_include_tags %>
    <%= stylesheet_link_tag 'application_asset', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :head %>
  </head>

  <body>
    <div class="container" style="max-width: 600px; width: 580px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>